config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users
  resources :posts do
    member { get :vote_up }
    member { get :vote_down }
    collection { get :search }
    resources :comments do
      member { get :vote_up }
      member { get :vote_down }
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  topic        :string
#  content_md   :text
#  content_html :text
#  last_update  :datetime
#  created_at   :datetime
#  updated_at   :datetime
#  score        :integer          default(0)
#

class Post < ActiveRecord::Base
  include Elasticsearch::Model # enables search
  include Elasticsearch::Model::Callbacks # any changes to model will update index
  include PostUpdatable

  validates :topic, :presence => true
  validates :content_md, :presence => true

  # update the post last_update column before saving
  before_save :update_post_last_update_timestamp
  before_update :update_post_last_update_timestamp

  has_many :comments, :dependent => :destroy
  belongs_to :user
  has_many :votes, as: :votable
end

app/controllers/posts_controller.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  topic        :string
#  content_md   :text
#  content_html :text
#  last_update  :datetime
#  created_at   :datetime
#  updated_at   :datetime
#  score        :integer          default(0)
#

class PostsController < ApplicationController
  before_action :check_if_admin, :only => [:destroy]
  before_action :check_if_logged_in, :only => [:new, :create, :edit, :update, :vote_up, :vote_down]
  before_action :check_if_author, :only => [:edit, :update]
  before_action :show_users_votes, :only => [:show]

  include Votable

  def index
    @posts = Post.all.order(:created_at => :desc)
    js false # tell paloma to ignore action
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new post_params
    post.user_id = session[:user_id]
    if post.save
      vote 1, 'post', post.id, session[:user_id]
      redirect_to posts_path
    else
      @post = post
      render :new
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    post = Post.find params[:id]
    if post.update post_params
      redirect_to post
    else
      @post = post
      render :edit
    end
  end

  def show
    @post = Post.find params[:id]
  end

  def destroy
    post = Post.find params[:id]
    post.destroy # associated comments will be auto deleted as defined in post model
    redirect_to posts_path
  end

  def search
    @posts = Post.search(params[:q]).records
    render :index
    js false # tell paloma to ignore action
  end

  def vote_up
    respond_to do |format|
      score = vote(1, 'Post', params[:id], session[:user_id])
      if !score.nil?
        format.html { redirect_to post_path params[:id] }
        format.js { render :json => { :status => 'ok', :score => score } }
      else
        format.html { redirect_to post_path params[:id] }
        format.js { render :json => { :status => 'error' } }
      end
    end
    js false # tell paloma to ignore action
  end

  def vote_down
    respond_to do |format|
      score = vote(-1, 'Post', params[:id], session[:user_id])
      if !score.nil?
        format.html { redirect_to post_path params[:id] }
        format.js { render :json => { :status => 'ok', :score => score } }
      else
        format.html { redirect_to post_path params[:id] }
        format.js { render :json => { :status => 'error' } }
      end
    end
    js false # tell paloma to ignore action
  end

  private
  def post_params
    params.require(:post).permit(:topic, :content_md, :content_html)
  end

  def check_if_logged_in
    redirect_to post_path(params[:id]) unless @current_user.present?
  end

  def check_if_admin
    redirect_to post_path(params[:id]) unless @current_user.present? && @current_user.admin?
  end

  # author can be post creator or admin
  def check_if_author
    post = Post.find params[:id]
    redirect_to post_path(params[:id]) unless @current_user.present? && (@current_user.id == post.user.id || @current_user.admin?)
  end

  # retrieve current users votes so we can display them in green in the show post view
  def show_users_votes
    return if @current_user.nil?
    postVote = @current_user.votes.find_by(:votable_type => 'Post', :votable_id => params[:id])
    commentVotes = @current_user.votes.where(:votable_type => 'Comment').select { |comment| comment.votable.post.id == params[:id].to_i }
    @votes = {}
    @votes[:post] = postVote.value unless postVote.nil?
    @votes[:comments] = {} unless commentVotes.nil?
    commentVotes.each do |commentVote|
      @votes[:comments][commentVote.votable_id.to_s.to_sym] = commentVote.value
    end
  end
end

app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  topic        :string
#  content_md   :text
#  content_html :text
#  last_update  :datetime
#  created_at   :datetime
#  updated_at   :datetime
#  score        :integer          default(0)
#

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

  <% if @post.errors.present? && @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
    <%= f.label :topic %>
  <div class="form-group">
    <div class="col-lg-12">
    <%= f.text_field :topic, :required => true, :class => 'form-control' %>
    <%=f.error_span(:topic) %>
    </div>
  </div>

<div class="row">
<div id="popoverWrapper" class="col-lg-7"></div>
</div>

  <div class="form-group">
    <div class="col-lg-6">
      <%= f.label :content_md, :Content %>
      <%= render :partial => 'posts/markdownHelpPopover' %>
      <%= f.text_area :content_md, :required => true, :class => 'form-control md-input' %>
    </div>
    <div class="col-lg-6">
      <%= f.label "Live markdown to HTML preview" %>
      <div class="preview content-html">
        <%== @post.content_html %>
      </div>
      <%= f.hidden_field :content_html %>
    </div>
    <%=f.error_span(:content_md) %>
  </div>

  <div class="form-group">
    <div class="col-lg-12">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                posts_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/posts/_markdownHelpPopover.html.erb
<a id="markdown-help" tabindex="0" class="btn btn-xs" role="button" data-toggle="popover" title="Markdown help" data-html="true" data-container="#popoverWrapper" data-content="
<p class=&quot;text-center&quot;>When creating a post/comment, write any text in <a href=&quot;https://en.wikipedia.org/wiki/Markdown&quot; target=&quot;_blank&quot;>markdown</a> in the content area below and it will automatically be converted to what you see in the live preview section. The following table lists a subset of <a href=&quot;http://spec.commonmark.org/0.24&quot; target=&quot;_blank&quot;>what can be done</a> in markdown:</p>

<div class=&quot;table-responsive&quot;>
  <table class=&quot;table-condensed table-bordered&quot;>
    <tr>
      <th>Markdown</th>
      <th>Output</th>
    </tr>
    <tr>
      <td>Text on<br><br>multiple lines</td>
      <td>Text on<br>multiple lines</td>
    </tr>
    <tr>
      <td>[link](http://example.com &quot;Title&quot;)<br>www.google.com</td>
      <td><a href=&quot;http://example.com&quot; title=&quot;Title&quot;>link</a><br><a href=&quot;www.example.com&quot;>www.example.com</a></td>
    </tr>
    <tr>
      <td>*Emphasize* _Emphasize_ <br> **Strong** __Strong__ <br> ~~boo boo~~</td>
      <td><em>Emphasize</em> <br> <strong>Strong</strong> <br> <s>boo boo</s></td>
    </tr>
    <tr>
      <td>![Bill](http://fillmurray.com/100/100)</td>
      <td><img src=&quot;http://fillmurray.com/100/100&quot;></td>
    </tr>
    <tr>
      <td>Asterisk/dash: <br> * Item <br> * Item <br> - Item <br> - Item <br></td>
      <td><ul>
        <li>Item</li>
        <li>Item</li>
        <li>Item</li>
        <li>Item</li>
      </ul></td>
    </tr>
    <tr>
      <td>1. Item <br>2. Item <br> &nbsp;&nbsp; * sub item</td>
      <td><ol>
        <li>Item</li>
        <li>Item</li>
        <ul><li>sub item</li></ul>
      </ol></td>
    </tr>
    <tr>
      <td>`inlline code`</td>
      <td><code>inline code</code></td>
    </tr>
    <tr>
      <td>
  ```css<br>
  #button { <br>
    border: none; <br>
  } <br>
  ```</td>
      <td>
  <pre><code class=&quot;language-css&quot;><span class=&quot;line&quot;><span class=&quot;id&quot;><span class=&quot;id&quot;>#button</span></span> <span class=&quot;rules&quot;><span class=&quot;rules&quot;>{
</span></span></span><span class=&quot;line&quot;><span class=&quot;rules&quot;><span class=&quot;rule&quot;><span class=&quot;attribute&quot;><span class=&quot;rules&quot;><span class=&quot;rule&quot;><span class=&quot;attribute&quot;>border</span></span></span></span><span class=&quot;rules&quot;><span class=&quot;rule&quot;>:</span></span><span class=&quot;value&quot;><span class=&quot;rules&quot;><span class=&quot;rule&quot;><span class=&quot;value&quot;> none</span></span></span></span></span><span class=&quot;rules&quot;>;
</span></span></span><span class=&quot;line&quot;><span class=&quot;rules&quot;><span class=&quot;rule&quot;><span class=&quot;rules&quot;><span class=&quot;rule&quot;>}</span></span></span></span></span></code></pre>
      </td>
    </tr>
    <tr>
      <td># Header 1 <br> ## Header 2</td>
      <td><h1>Header 1</h1><br><h2>Header 2</h2></td>
    </tr>
    <tr>
      <td>First name | Last name <br> --- | --- <br> Bill | Murray</td>
      <td>
<table>
<thead>
<tr>
<th>First name</th>
<th>Last name</th>
</tr>
</thead>
<tbody>
<tr>
<td>Bill</td>
<td>Murray</td>
</tr>
</tbody>
</table>
      </td>
    </tr>
  </table>
</div>
">Markdown help?</a>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>Edit post</h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>All posts</h1>
</div>

<% if @current_user.present? %>
  <%= link_to 'New post',
new_post_path,
:class => 'btn btn-primary' %>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Votes</th>
      <th>Topic</th>
      <th>Author</th>
      <th>Replies</th>
      <th>Created</th>
      <th>Last updated</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.score %></td>
        <td><%= link_to(post.topic, post) %></td>
        <td><%= post.user.name %></td>
        <td><%= post.comments.count %></td>
        <td><%= post.created_at.strftime('%I:%M %P %a %e %b %Y') %></td>
        <td><%= time_ago_in_words(post.last_update || post.updated_at) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1>New Post</h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%= @post.topic %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <div class="col-md-1">
      <%= image_tag @post.user.image, :class => 'img-responsive' %>
    </div>
    <ul class="list-inline">
      <li><strong>Votes:</strong>
        <span class="score"><%= @post.score %></span>
        <% if @current_user.present? %>
            <%= link_to 'up', vote_up_post_path(@post), :class => "vote btn #{ @votes[:post] == 1 ? 'btn-success' : 'btn-default' }", :role => 'button', :data => { :remote => true, :type => 'json', :vote => 'up' } %>
            <%= link_to 'down', vote_down_post_path(@post), :class => "vote btn #{ @votes[:post] == -1 ? 'btn-success' : 'btn-default' }", :role => 'button', :data => { :remote => true, :type => 'json', :vote => 'down' } %>
        <% end %>
      </li>
      <li><strong>Author:</strong>
      <%= @post.user.name %>
      </li>
      <li><strong>Created:</strong>
      <%= @post.created_at.strftime '%a %d %b %Y at %H:%M' %>
      </li>
      <li><strong>Updated:</strong>
      <%= time_ago_in_words @post.updated_at %>
      </li>
    </ul>
  </div>
  <div class="panel-body content-html"><%== @post.content_html %></div>
</div>

<% @post.comments.order(:created_at).each do |comment| %>
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <div class="col-md-1">
      <%= image_tag comment.user.image, :class => 'img-responsive' %>
    </div>
    <ul class="list-inline">
      <li><strong>Votes:</strong>
        <span class="score"><%= comment.score %></span>
        <% if @current_user.present? %>
          <%= link_to 'up', vote_up_post_comment_path(@post, comment), :class => "vote btn #{ @votes[:comments][comment.id.to_s.to_sym] == 1 ? 'btn-success' : 'btn-default' }", :role => 'button', :data => { :remote => true, :type => 'json' } %>
          <%= link_to 'down', vote_down_post_comment_path(@post, comment), :class => "vote btn #{ @votes[:comments][comment.id.to_s.to_sym] == -1 ? 'btn-success' : 'btn-default' }", :role => 'button', :data => { :remote => true, :type => 'json' }  %>
        <% end %>
      </li>
      <li><strong>Author:</strong>
      <%= comment.user.name %>
      </li>
      <li><strong>Created:</strong>
      <%= comment.created_at.strftime '%a %d %b %Y at %H:%M' %>
      </li>
      <li><strong>Updated:</strong>
      <%= time_ago_in_words comment.updated_at %>
      </li>
    </ul>
    <% if @current_user.present? && @current_user.id == comment.user.id %>
      <%= link_to 'Edit comment', edit_post_comment_path(@post, comment), :class => 'btn btn-default', :role => 'button' %>
    <% end %>

    <% if @current_user.present? && @current_user.admin? %>
      <%= link_to 'Delete comment', post_comment_path(@post, comment), :method => :delete, :data => { :confirm => "Are you sure?"}, :class => 'btn btn-default', :role => 'button' %>
    <% end %>
  </div>
  <div class="panel-body content-html"><%== comment.content_html %></div>
</div>
<% end %>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>

<% if @current_user.present? %>
    <%= link_to 'Add comment', new_post_comment_path(@post), :class => 'btn btn-default' %>
  <% end %>

  <% if @current_user.present? && (@current_user.id == @post.user.id || @current_user.admin?) %>
    <%= link_to 'Edit post',
              edit_post_path(@post), :class => 'btn btn-default' %>
  <% end %>

  <% if @current_user.present? && @current_user.admin? %>
    <%= link_to 'Delete post',
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => 'Are you sure?' },
              :class => 'btn btn-danger' %>
  <% end %>