config/routes.rb
Rails.application.routes.draw do
  root :to => 'posts#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users
  resources :posts do
    member { get :vote_up }
    member { get :vote_down }
    collection { get :search }
    resources :comments do
      member { get :vote_up }
      member { get :vote_down }
    end
  end
end

app/views/layouts/_navbar.html.erb
 <div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">SlackOverflow</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'All posts', posts_path %></li>
        <% if @current_user.present? && @current_user.admin? %>
            <li><%= link_to 'All users', users_path %></li>
        <% end %>
      </ul>
      <%= form_tag(search_posts_path, :method => :get, :class => 'navbar-form pull-right') do %>
        <%= text_field_tag :q, params[:q], :placeholder => 'Search posts', :class => 'span2' %>
        <%= submit_tag :Find, :class => 'btn btn-default' %>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user.present? %>
          <li><%= link_to @current_user.name.capitalize, @current_user %></li>
          <li><%= link_to 'Log out', logout_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', new_user_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SlackOverflow</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

  <%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
          <%= insert_paloma_hook %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>